bluez: Fix IUTCtl
6b59bde29 introduces support for controller selection with per IUT
contexts and stacks, which can be resolved by call to get_iut() and
get_stack().

This currently crashes for BlueZ:
Traceback (most recent call last):
  File "/home/fdanis/src/auto-pts/./autoptsclient-bluez.py", line 40, in <module>
    main()
  File "/home/fdanis/src/auto-pts/./autoptsclient-bluez.py", line 36, in main
    client.start()
  File "/home/fdanis/src/auto-pts/autopts/client.py", line 1535, in start
    return self.main(args)
           ^^^^^^^^^^^^^^^
  File "/home/fdanis/src/auto-pts/autopts/client.py", line 1590, in main
    self.setup_test_cases(self.ptses)
  File "/home/fdanis/src/auto-pts/autopts/client.py", line 1613, in setup_test_cases
    self.test_cases = setup_test_cases(ptses)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fdanis/src/auto-pts/autopts/client.py", line 1831, in setup_test_cases
    test_cases += mod.test_cases(ptses)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fdanis/src/auto-pts/autopts/ptsprojects/bluez/bap.py", line 90, in test_cases
    stack = get_stack()
            ^^^^^^^^^^^
  File "/home/fdanis/src/auto-pts/autopts/ptsprojects/stack/stack.py", line 305, in get_stack
    return _get_stack()
           ^^^^^^^^^^^^
  File "/home/fdanis/src/auto-pts/autopts/pybtp/btp/btp.py", line 687, in _get_stack
    return get_iut().get_stack()
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'IUTCtl' object has no attribute 'get_stack'

This also add default log_file for BTPSocketSrv.